// <auto-generated />
using System;
using EntityArchitect.CRUD.Entities.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Paris2025.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251115171908_init4")]
    partial class init4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EntityArchitect.CRUD.Application.EndpointMap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Accesses")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("accesses");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hash");

                    b.Property<string>("HttpMethod")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("http_method");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("path");

                    b.HasKey("Id")
                        .HasName("pk___endpoint_map");

                    b.ToTable("__EndpointMap", (string)null);
                });

            modelBuilder.Entity("Paris2025.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool?>("BillingAddressMatchesShippingAddress")
                        .HasColumnType("boolean")
                        .HasColumnName("billing_address_matches_shipping_address");

                    b.Property<string>("Billing_Address_1")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("billing_address_1");

                    b.Property<string>("Billing_Address_2")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("billing_address_2");

                    b.Property<string>("Billing_City")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("billing_city");

                    b.Property<string>("Billing_Country")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("billing_country");

                    b.Property<string>("Billing_Province")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("billing_province");

                    b.Property<string>("Billing_Zip")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("billing_zip");

                    b.Property<bool?>("CanMarkAsPaid")
                        .HasColumnType("boolean")
                        .HasColumnName("can_mark_as_paid");

                    b.Property<DateTime?>("CancelDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancel_date");

                    b.Property<bool?>("CannotNotifyCustomer")
                        .HasColumnType("boolean")
                        .HasColumnName("cannot_notify_customer");

                    b.Property<string>("ClientIp")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("client_ip");

                    b.Property<DateTime?>("CloseDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("close_date");

                    b.Property<bool>("Closed")
                        .HasColumnType("boolean")
                        .HasColumnName("closed");

                    b.Property<string>("ConfirmationNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("confirmation_number");

                    b.Property<bool>("Confirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("confirmed");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Currency")
                        .HasColumnType("integer")
                        .HasColumnName("currency");

                    b.Property<bool?>("CustomerAcceptsMarketing")
                        .HasColumnType("boolean")
                        .HasColumnName("customer_accepts_marketing");

                    b.Property<string>("CustomerLocale")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("customer_locale");

                    b.Property<string>("Customer_Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("customer_email");

                    b.Property<string>("Customer_Id")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("customer_id");

                    b.Property<string>("Customer_Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("customer_name");

                    b.Property<bool>("DutiesIncluded")
                        .HasColumnType("boolean")
                        .HasColumnName("duties_included");

                    b.Property<bool?>("Fulfillable")
                        .HasColumnType("boolean")
                        .HasColumnName("fulfillable");

                    b.Property<int>("FulfillmentStatus")
                        .HasColumnType("integer")
                        .HasColumnName("fulfillment_status");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("order_date");

                    b.Property<string>("OrderName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("order_name");

                    b.Property<string>("PoNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("po_number");

                    b.Property<int>("PresentmentCurrency")
                        .HasColumnType("integer")
                        .HasColumnName("presentment_currency");

                    b.Property<bool?>("RequiresShipping")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_shipping");

                    b.Property<string>("Shipping_Address_1")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("shipping_address_1");

                    b.Property<string>("Shipping_Address_2")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("shipping_address_2");

                    b.Property<string>("Shipping_City")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("shipping_city");

                    b.Property<string>("Shipping_Country")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("shipping_country");

                    b.Property<string>("Shipping_Province")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("shipping_province");

                    b.Property<string>("Shipping_Zip")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("shipping_zip");

                    b.Property<string>("SourceIdentifier")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_identifier");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_name");

                    b.Property<long>("SrcOrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("src_order_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<decimal>("SubtotalPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("subtotal_price");

                    b.Property<bool>("TaxesIncluded")
                        .HasColumnType("boolean")
                        .HasColumnName("taxes_included");

                    b.Property<bool>("Taxexempt")
                        .HasColumnType("boolean")
                        .HasColumnName("taxexempt");

                    b.Property<bool>("Test")
                        .HasColumnType("boolean")
                        .HasColumnName("test");

                    b.Property<decimal>("TotalDiscounts")
                        .HasColumnType("numeric")
                        .HasColumnName("total_discounts");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("total_price");

                    b.Property<decimal>("TotalRefunded")
                        .HasColumnType("numeric")
                        .HasColumnName("total_refunded");

                    b.Property<decimal>("TotalShipping")
                        .HasColumnType("numeric")
                        .HasColumnName("total_shipping");

                    b.Property<decimal>("TotalTax")
                        .HasColumnType("numeric")
                        .HasColumnName("total_tax");

                    b.Property<decimal>("TotalTip")
                        .HasColumnType("numeric")
                        .HasColumnName("total_tip");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_order");

                    b.ToTable("order", (string)null);
                });

            modelBuilder.Entity("Paris2025.Entities.OrderProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Currency")
                        .HasColumnType("integer")
                        .HasColumnName("currency");

                    b.Property<decimal>("DiscountedPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("discounted_price");

                    b.Property<decimal>("DiscountedUnitPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("discounted_unit_price");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<decimal>("OrginalUnitPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("orginal_unit_price");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<bool>("RequiresShipping")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_shipping");

                    b.Property<bool>("Taxable")
                        .HasColumnType("boolean")
                        .HasColumnName("taxable");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_order_product");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_order_product_order_id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_order_product_product_id");

                    b.ToTable("order_product", (string)null);
                });

            modelBuilder.Entity("Paris2025.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CategoryFullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category_full_name");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category_id");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DescriptionHtml")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description_html");

                    b.Property<bool>("HasOnlyDefaultVariant")
                        .HasColumnType("boolean")
                        .HasColumnName("has_only_default_variant");

                    b.Property<bool>("HasOutOfStockVariants")
                        .HasColumnType("boolean")
                        .HasColumnName("has_out_of_stock_variants");

                    b.Property<string>("InventoryProductType")
                        .HasColumnType("text")
                        .HasColumnName("inventory_product_type");

                    b.Property<int?>("InventoryStatus")
                        .HasColumnType("integer")
                        .HasColumnName("inventory_status");

                    b.Property<string>("InventoryTitle")
                        .HasColumnType("text")
                        .HasColumnName("inventory_title");

                    b.Property<int?>("InventoryTotalInventory")
                        .HasColumnType("integer")
                        .HasColumnName("inventory_total_inventory");

                    b.Property<string>("InventoryVendor")
                        .HasColumnType("text")
                        .HasColumnName("inventory_vendor");

                    b.Property<bool>("IsGiftCard")
                        .HasColumnType("boolean")
                        .HasColumnName("is_gift_card");

                    b.Property<decimal>("PriceCurrent")
                        .HasColumnType("numeric")
                        .HasColumnName("price_current");

                    b.Property<decimal>("PriceMax")
                        .HasColumnType("numeric")
                        .HasColumnName("price_max");

                    b.Property<decimal>("PriceMin")
                        .HasColumnType("numeric")
                        .HasColumnName("price_min");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("product_type");

                    b.Property<bool>("RequiresSellingPlan")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_selling_plan");

                    b.Property<string>("SeoDescription")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("seo_description");

                    b.Property<string>("SeoTitle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("seo_title");

                    b.Property<long>("SrcProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("src_product_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<int>("TotalInventory")
                        .HasColumnType("integer")
                        .HasColumnName("total_inventory");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Vendor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("vendor");

                    b.HasKey("Id")
                        .HasName("pk_product");

                    b.ToTable("product", (string)null);
                });

            modelBuilder.Entity("Paris2025.Entities.Variant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CategoryFullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category_full_name");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category_id");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DescriptionHtml")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description_html");

                    b.Property<bool>("HasOnlyDefaultVariant")
                        .HasColumnType("boolean")
                        .HasColumnName("has_only_default_variant");

                    b.Property<bool>("HasOutOfStockVariants")
                        .HasColumnType("boolean")
                        .HasColumnName("has_out_of_stock_variants");

                    b.Property<bool>("IsGiftCard")
                        .HasColumnType("boolean")
                        .HasColumnName("is_gift_card");

                    b.Property<decimal>("PriceCurrent")
                        .HasColumnType("numeric")
                        .HasColumnName("price_current");

                    b.Property<decimal>("PriceMax")
                        .HasColumnType("numeric")
                        .HasColumnName("price_max");

                    b.Property<decimal>("PriceMin")
                        .HasColumnType("numeric")
                        .HasColumnName("price_min");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("product_type");

                    b.Property<bool>("RequiresSellingPlan")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_selling_plan");

                    b.Property<string>("SeoDescription")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("seo_description");

                    b.Property<string>("SeoTitle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("seo_title");

                    b.Property<long>("SrcProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("src_product_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<int>("TotalInventory")
                        .HasColumnType("integer")
                        .HasColumnName("total_inventory");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Vendor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("vendor");

                    b.HasKey("Id")
                        .HasName("pk_variant");

                    b.HasIndex("ProductId")
                        .IsUnique()
                        .HasDatabaseName("ix_variant_product_id");

                    b.ToTable("variant", (string)null);
                });

            modelBuilder.Entity("Paris2025.Entities.VariantProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("VariantId")
                        .HasColumnType("uuid")
                        .HasColumnName("variant_id");

                    b.HasKey("Id")
                        .HasName("pk_variant_product");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_variant_product_product_id");

                    b.ToTable("variant_product", (string)null);
                });

            modelBuilder.Entity("Paris2025.Entities.OrderProduct", b =>
                {
                    b.HasOne("Paris2025.Entities.Order", "Order")
                        .WithMany("OrderProducts")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_product_order_order_id");

                    b.HasOne("Paris2025.Entities.Product", "Product")
                        .WithMany("OrderProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_product_product_product_id");

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Paris2025.Entities.Variant", b =>
                {
                    b.HasOne("Paris2025.Entities.VariantProduct", "Product")
                        .WithOne("Variant")
                        .HasForeignKey("Paris2025.Entities.Variant", "ProductId")
                        .HasConstraintName("fk_variant_variant_product_product_id");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Paris2025.Entities.VariantProduct", b =>
                {
                    b.HasOne("Paris2025.Entities.Product", "Product")
                        .WithMany("Variants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_variant_product_product_product_id");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Paris2025.Entities.Order", b =>
                {
                    b.Navigation("OrderProducts");
                });

            modelBuilder.Entity("Paris2025.Entities.Product", b =>
                {
                    b.Navigation("OrderProducts");

                    b.Navigation("Variants");
                });

            modelBuilder.Entity("Paris2025.Entities.VariantProduct", b =>
                {
                    b.Navigation("Variant")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
