using System.Reflection;
using Npgsql;
using Paris2025.Entities;

namespace Paris2025.Services;

public class OrderProductMapper
{
    /// <summary>
    /// Maps database row to OrderProduct entity
    /// OrderProduct has foreign keys: product_id, order_id (using name_id pattern)
    /// </summary>
    public static OrderProduct MapFromReader(NpgsqlDataReader reader)
    {
        var orderProduct = new OrderProduct();

        // Map id column if exists (Guid - auto-generated by EntityArchitect)
        var idIndex = GetColumnIndex(reader, "id");
        if (idIndex >= 0 && !reader.IsDBNull(idIndex))
        {
            var idProperty = typeof(OrderProduct).BaseType?.GetProperty("Id") 
                            ?? typeof(OrderProduct).GetProperty("Id");
            if (idProperty != null && idProperty.CanWrite)
            {
                var idValue = reader.GetValue(idIndex);
                if (idValue is Guid guidValue)
                {
                    idProperty.SetValue(orderProduct, guidValue);
                }
                else if (idValue is string guidString && Guid.TryParse(guidString, out var parsedGuid))
                {
                    idProperty.SetValue(orderProduct, parsedGuid);
                }
            }
        }

        // Map product_id foreign key (name_id pattern) - Guid type
        var productIdIndex = GetColumnIndex(reader, "product_id");
        if (productIdIndex >= 0 && !reader.IsDBNull(productIdIndex))
        {
            var productId = GetGuidFromReader(reader, productIdIndex);
            // Store the foreign key - navigation property will be set when loading related entities
        }

        // Map order_id foreign key (name_id pattern) - Guid type
        var orderIdIndex = GetColumnIndex(reader, "order_id");
        if (orderIdIndex >= 0 && !reader.IsDBNull(orderIdIndex))
        {
            var orderId = GetGuidFromReader(reader, orderIdIndex);
            // Store the foreign key - navigation property will be set when loading related entities
        }

        return orderProduct;
    }

    /// <summary>
    /// Generates SQL INSERT statement for OrderProduct with foreign key columns
    /// Note: Id is auto-generated by EntityArchitect, so it's not included in INSERT
    /// New entities use snake_case table name without 's': OrderProduct -> order_product
    /// </summary>
    public static string GenerateInsertSql(OrderProduct orderProduct)
    {
        return @"INSERT INTO order_product (product_id, order_id)
                 VALUES (@product_id, @order_id)";
    }

    /// <summary>
    /// Adds parameters for INSERT, including foreign key columns with name_id pattern
    /// Foreign keys: product_id, order_id
    /// </summary>
    public static void AddInsertParameters(NpgsqlCommand command, OrderProduct orderProduct)
    {
        // Extract Guid Id from Product navigation property (name_id pattern: product_id)
        var productId = GetEntityId(orderProduct.Product);
        command.Parameters.AddWithValue("product_id", productId.HasValue ? (object)productId.Value : DBNull.Value);

        // Extract Guid Id from Order navigation property (name_id pattern: order_id)
        var orderId = GetEntityId(orderProduct.Order);
        command.Parameters.AddWithValue("order_id", orderId.HasValue ? (object)orderId.Value : DBNull.Value);
    }

    private static int GetColumnIndex(NpgsqlDataReader reader, string columnName)
    {
        try
        {
            return reader.GetOrdinal(columnName);
        }
        catch
        {
            return -1;
        }
    }

    private static Guid? GetEntityId(object? entity)
    {
        if (entity == null) return null;

        var idProperty = entity.GetType().BaseType?.GetProperty("Id") 
                        ?? entity.GetType().GetProperty("Id");
        
        if (idProperty != null)
        {
            var idValue = idProperty.GetValue(entity);
            if (idValue is Guid guidValue)
            {
                return guidValue;
            }
            if (idValue != null && Guid.TryParse(idValue.ToString(), out var parsedGuid))
            {
                return parsedGuid;
            }
        }

        return null;
    }

    private static Guid? GetGuidFromReader(NpgsqlDataReader reader, int index)
    {
        try
        {
            var value = reader.GetValue(index);
            if (value is Guid guidValue)
            {
                return guidValue;
            }
            if (value is string guidString && Guid.TryParse(guidString, out var parsedGuid))
            {
                return parsedGuid;
            }
            return null;
        }
        catch
        {
            return null;
        }
    }
}

