using System.Reflection;
using Npgsql;
using Paris2025.Entities;

namespace Paris2025.Services;

public class VariantProductMapper
{
    /// <summary>
    /// Maps database row to VariantProduct entity
    /// VariantProduct has foreign keys: product_id, variant_id
    /// </summary>
    public static VariantProduct MapFromReader(NpgsqlDataReader reader)
    {
        var variantProduct = new VariantProduct();

        // Map id column if exists (Guid - auto-generated by EntityArchitect)
        var idIndex = GetColumnIndex(reader, "id");
        if (idIndex >= 0 && !reader.IsDBNull(idIndex))
        {
            var idProperty = typeof(VariantProduct).BaseType?.GetProperty("Id") 
                            ?? typeof(VariantProduct).GetProperty("Id");
            if (idProperty != null && idProperty.CanWrite)
            {
                var idValue = reader.GetValue(idIndex);
                if (idValue is Guid guidValue)
                {
                    idProperty.SetValue(variantProduct, guidValue);
                }
                else if (idValue is string guidString && Guid.TryParse(guidString, out var parsedGuid))
                {
                    idProperty.SetValue(variantProduct, parsedGuid);
                }
            }
        }

        // Map product_id foreign key (name_id pattern) - Guid type
        var productIdIndex = GetColumnIndex(reader, "product_id");
        if (productIdIndex >= 0 && !reader.IsDBNull(productIdIndex))
        {
            var productId = GetGuidFromReader(reader, productIdIndex);
            // Store the foreign key - navigation property will be set when loading related entities
        }

        // Map variant_id foreign key (name_id pattern) - Guid type
        var variantIdIndex = GetColumnIndex(reader, "variant_id");
        if (variantIdIndex >= 0 && !reader.IsDBNull(variantIdIndex))
        {
            var variantId = GetGuidFromReader(reader, variantIdIndex);
            // Store the foreign key - navigation property will be set when loading related entities
        }

        return variantProduct;
    }

    /// <summary>
    /// Generates SQL INSERT statement for VariantProduct with foreign key columns
    /// Note: Id is auto-generated by EntityArchitect, so it's not included in INSERT
    /// New entities use snake_case table name without 's': VariantProduct -> variant_product
    /// </summary>
    public static string GenerateInsertSql(VariantProduct variantProduct)
    {
        return @"INSERT INTO variant_product (product_id, variant_id)
                 VALUES (@product_id, @variant_id)";
    }

    /// <summary>
    /// Adds parameters for INSERT, including foreign key columns with name_id pattern
    /// Foreign keys: product_id, variant_id
    /// </summary>
    public static void AddInsertParameters(NpgsqlCommand command, VariantProduct variantProduct)
    {
        // Extract Guid Id from Product navigation property (name_id pattern: product_id)
        var productId = GetEntityId(variantProduct.Product);
        command.Parameters.AddWithValue("product_id", productId.HasValue ? (object)productId.Value : DBNull.Value);

        // Extract Guid Id from Variant navigation property (name_id pattern: variant_id)
        var variantId = GetEntityId(variantProduct.Variant);
        command.Parameters.AddWithValue("variant_id", variantId.HasValue ? (object)variantId.Value : DBNull.Value);
    }

    private static int GetColumnIndex(NpgsqlDataReader reader, string columnName)
    {
        try
        {
            return reader.GetOrdinal(columnName);
        }
        catch
        {
            return -1;
        }
    }

    private static Guid? GetEntityId(object? entity)
    {
        if (entity == null) return null;

        var idProperty = entity.GetType().BaseType?.GetProperty("Id") 
                        ?? entity.GetType().GetProperty("Id");
        
        if (idProperty != null)
        {
            var idValue = idProperty.GetValue(entity);
            if (idValue is Guid guidValue)
            {
                return guidValue;
            }
            if (idValue != null && Guid.TryParse(idValue.ToString(), out var parsedGuid))
            {
                return parsedGuid;
            }
        }

        return null;
    }

    private static Guid? GetGuidFromReader(NpgsqlDataReader reader, int index)
    {
        try
        {
            var value = reader.GetValue(index);
            if (value is Guid guidValue)
            {
                return guidValue;
            }
            if (value is string guidString && Guid.TryParse(guidString, out var parsedGuid))
            {
                return parsedGuid;
            }
            return null;
        }
        catch
        {
            return null;
        }
    }
}

